title: SharePoint REST Framework
description: An easy way to create, read, update and delete data using the SharePoint 2013/Online REST API
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
